### ISSUE TITLE
IndexError remove_stretched_faces

### ISSUE THREAD

**Issue by andreiburov** [YuliangXiu/ECON#24]
Thank you very much for publishing your work. I have tried to run it on the subset of the People Snapshot Dataset, you can find it in the zip file, and get the following error. Do you have an idea, how to fix it?

```bash
Body Fitting -- normal: 0.000 | silhouette: 0.143 | joint: 0.409 | Total: 0.552| loose:1, occluded:0: 100%|██████████| 50/50 [00:07<00:00,  6.69it/s]
0:   0%|          | 0/130 [04:28<?, ?it/s]: 0.143 | joint: 0.409 | Total: 0.552| loose:1, occluded:0: 100%|██████████| 50/50 [00:07<00:00,  6.46it/s]
Traceback (most recent call last):
  File ".../Miniconda3/envs/econ/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".../Miniconda3/envs/econ/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".../Projects/ECON/apps/infer.py", line 478, in <module>
    BNI_object.extract_surface(False)
  File ".../Projects/ECON/lib/common/BNI.py", line 45, in extract_surface
    bni_result = double_side_bilateral_normal_integration(
  File ".../Projects/ECON/lib/common/BNI_utils.py", line 640, in double_side_bilateral_normal_integration
    vertices_front, faces_front = remove_stretched_faces(vertices_front, faces_front)
  File ".../Projects/ECON/lib/common/BNI_utils.py", line 124, in remove_stretched_faces
    faces_cam_angles = np.dot(mesh.face_normals, camera_ray)
  File ".../Miniconda3/envs/econ/lib/python3.8/site-packages/trimesh/base.py", line 340, in face_normals
    triangles=self.triangles,
  File ".../Miniconda3/envs/econ/lib/python3.8/site-packages/trimesh/caching.py", line 139, in get_cached
    value = function(*args, **kwargs)
  File ".../Miniconda3/envs/econ/lib/python3.8/site-packages/trimesh/base.py", line 783, in triangles
    triangles = self.vertices.view(np.ndarray)[self.faces]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

[female-130.zip](https://github.com/YuliangXiu/ECON/files/10581478/female-130.zip)

**Comment by YuliangXiu** [comment]
Hi Andrei, excited to know that you are interested in ECON!

I tried the images you provided and ECON works well on them. There seems to be a bug from `trimesh`, maybe you could upgrade `trimesh==3.17.1` with `pip install trimesh --upgrade` and then re-run the inference.

`remove_stretched_faces` is just to remove the triangles perpendicular with camera-ray (z-axis), you can also uncomment this line to see if the inference runs well.

![0_cloth](https://user-images.githubusercontent.com/7944350/216745286-7ef7aaf3-0789-4302-8ce1-4c4a214b8297.png)

**Comment by andreiburov** [comment]
Thank you for such a quick response!

I have tried both options you suggested.

Please find my list of conda packages here - [conda.txt](https://github.com/YuliangXiu/ECON/files/10677821/conda.txt)
I have tried both trimesh==3.18.3 and then the downgraded version 3.17.1. It generates the same error.

Then, I tried to comment out several lines

https://github.com/YuliangXiu/ECON/blob/2b4d727ccd46a875755e13871e220feea893b6c2/lib/common/BNI_utils.py#L640
```
#vertices_front, faces_front = remove_stretched_faces(vertices_front, faces_front)
#vertices_back, faces_back = remove_stretched_faces(vertices_back, faces_back)
```

Leads to 

```
Traceback (most recent call last):
  File "/cluster/erebor/aburov/Miniconda3/envs/econ/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cluster/erebor/aburov/Miniconda3/envs/econ/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cluster/erebor/aburov/Projects/ECON/apps/infer.py", line 478, in <module>
    BNI_object.extract_surface(False)
  File "/cluster/erebor/aburov/Projects/ECON/lib/common/BNI.py", line 45, in extract_surface
    bni_result = double_side_bilateral_normal_integration(
  File "/cluster/erebor/aburov/Projects/ECON/lib/common/BNI_utils.py", line 643, in double_side_bilateral_normal_integration
    front_mesh = clean_floats(trimesh.Trimesh(vertices_front, faces_front))
  File "/cluster/erebor/aburov/Projects/ECON/lib/dataset/mesh_util.py", line 709, in clean_floats
    mesh_lst = mesh.split(only_watertight=False)
  File "/cluster/erebor/aburov/Miniconda3/envs/econ/lib/python3.8/site-packages/trimesh/constants.py", line 146, in timed
    result = method(*args, **kwargs)
  File "/cluster/erebor/aburov/Miniconda3/envs/econ/lib/python3.8/site-packages/trimesh/base.py", line 1270, in split
    return graph.split(self, **kwargs)
  File "/cluster/erebor/aburov/Miniconda3/envs/econ/lib/python3.8/site-packages/trimesh/graph.py", line 370, in split
    meshes = mesh.submesh(
  File "/cluster/erebor/aburov/Miniconda3/envs/econ/lib/python3.8/site-packages/trimesh/base.py", line 2692, in submesh
    return util.submesh(
  File "/cluster/erebor/aburov/Miniconda3/envs/econ/lib/python3.8/site-packages/trimesh/util.py", line 1564, in submesh
    mask[unique] = np.arange(len(unique))
IndexError: index 0 is out of bounds for axis 0 with size 0
```

While commenting out the next two lines

```
#vertices_front, faces_front = remove_stretched_faces(vertices_front, faces_front)
#vertices_back, faces_back = remove_stretched_faces(vertices_back, faces_back)

#front_mesh = clean_floats(trimesh.Trimesh(vertices_front, faces_front))
 #back_mesh = clean_floats(trimesh.Trimesh(vertices_back, faces_back))

 front_mesh = trimesh.Trimesh(vertices_front, faces_front)
 back_mesh = trimesh.Trimesh(vertices_back, faces_back)
```

Leads to

```
Traceback (most recent call last):
  File "/cluster/erebor/aburov/Miniconda3/envs/econ/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cluster/erebor/aburov/Miniconda3/envs/econ/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cluster/erebor/aburov/Projects/ECON/apps/infer.py", line 558, in <module>
    BNI_object.F_B_trimesh = part_removal(
  File "/cluster/erebor/aburov/Projects/ECON/lib/dataset/mesh_util.py", line 256, in part_removal
    BNI_part_mask = ~(remove_mask).flatten()[full_mesh.faces].any(dim=1)
IndexError: index is out of bounds for dimension with size 0
```

I'll try to look further, but maybe you already have some suggestions? Which package versions have you used originally?

**Comment by YuliangXiu** [comment]
I always used latest `trimesh` and it works well in my local machine.

**Comment by majid-podform3d** [comment]
Hi @andreiburov ,

By any chance, could you solve it?
I am experiencing exactly the same issue!

**Comment by YuliangXiu** [comment]
@majid-podform3d Thanks so much for your pointing out, I just updated the `requirements.txt`
