### ISSUE TITLE
IndexError: index 5484 is out of bounds for axis 0 with size 5023

### ISSUE THREAD

**Issue by dataangel** [YuliangXiu/ECON#35]
(base) H:\ECON-master>python -m apps.infer -cfg ./configs/econ.yaml -in_dir ./examples -out_dir ./results
Traceback (most recent call last):
  File "d:\tools\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\tools\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "H:\ECON-master\apps\infer.py", line 32, in <module>
    from apps.Normal import Normal
  File "H:\ECON-master\apps\Normal.py", line 2, in <module>
    from lib.common.train_util import batch_mean
  File "H:\ECON-master\lib\common\train_util.py", line 18, in <module>
    from ..dataset.mesh_util import *
  File "H:\ECON-master\lib\dataset\mesh_util.py", line 162, in <module>
    model_path=SMPLX().model_dir,
  File "H:\ECON-master\lib\dataset\mesh_util.py", line 92, in __init__
    self.smplx_front_flame_vid = self.smplx_flame_vid[np.load(self.front_flame_path)]
IndexError: index 5484 is out of bounds for axis 0 with size 5023

**Comment by YuliangXiu** [comment]
I tried to print the dim of `np.load(self.front_flame_path)`

```bash
print(np.load(self.front_flame_path).max())
3928
```

Did you download the right `smpl_data/FLAME_face_mask_ids.npy`?

**Comment by dataangel** [comment]
![image](https://user-images.githubusercontent.com/587849/226153862-f52a0fd3-f749-4c64-8c4b-a0b81a1c902a.png)
print(np.load(self.front_flame_path).max()) 
10474
我输出是这个

**Comment by YuliangXiu** [comment]
Interesting, could you share this file with me? 

Mailto: yuliang.xiu@tue.mpg.de

**Comment by dataangel** [comment]
![image](https://user-images.githubusercontent.com/587849/226174911-b64e628c-0700-4f5c-94eb-01a474135cac.png)

**Comment by YuliangXiu** [comment]
Have a try on `numpy==1.23.4`

**Comment by dataangel** [comment]
![image](https://user-images.githubusercontent.com/587849/226178327-5465f2d4-6d83-45f1-88c5-1e9d2ed50cbd.png)

**Comment by YuliangXiu** [comment]
Could you print out this matrix?

```bash
>>> np.load(path)
array([  16,   17,   18, ..., 3926, 3927, 3928])
>>> np.load(path).shape
(1609,)
```

**Comment by dataangel** [comment]
![image](https://user-images.githubusercontent.com/587849/226183007-6a5be85c-f9d5-4930-8fb2-443261444e7a.png)
(base) H:\ECON-master>python
Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.load('H:\ECON-master\lib\dataset\../../data/smpl_related\smpl_data/FLAME_face_mask_ids.npy')
array([    0,     1,     2, ..., 10472, 10473, 10474], dtype=int64)
>>> np.load('H:\ECON-master\lib\dataset\../../data/smpl_related\smpl_data/FLAME_face_mask_ids.npy').shape
(5023,)
