### ISSUE TITLE
issues when run the app.infer - multi

### ISSUE THREAD

**Issue by Wangzeda** [YuliangXiu/ECON#75]
Hi, Thanks for your great work. I am facing a weird issue when run the app/infer.py with multi setting

```bash
Resume Normal Estimator from  ./data/ckpt/normal.ckpt 
Complete with  SMPL-X (Explicit) 
SMPL-X estimate with  PIXIE 
Dataset Size: 1
  0%|                                                                                                                      | 0/1 [00:00<?, ?it/s]INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Register SMPL-X -> d-BiNI -- cloth:0.928 | stiff:1.139 | rigid:0.002 | lapla:0.191 | TOTAL: 2.260: 100%|███████| 100/100 [00:05<00:00, 19.30it/s]
2:   0%|                                                                                                                   | 0/1 [01:48<?, ?it/s]
Traceback (most recent call last):
  File "/data22/DISCOVER_summer2023/wangzd2306/.conda/envs/nerfecon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data22/DISCOVER_summer2023/wangzd2306/.conda/envs/nerfecon/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data22/DISCOVER_summer2023/wangzd2306/ECON/apps/infer.py", line 593, in <module>
    BNI_object.F_B_trimesh = part_removal(
  File "/data22/DISCOVER_summer2023/wangzd2306/ECON/lib/dataset/mesh_util.py", line 270, in part_removal
    (part_dist, _) = part_extractor.query(torch.tensor(full_mesh.vertices).unsqueeze(0).to(device))
  File "/data22/DISCOVER_summer2023/wangzd2306/ECON/lib/dataset/PointFeat.py", line 39, in query
    residues, pts_ind = point_mesh_distance(self.mesh, Pointclouds(points), weighted=False) # 使用point_mesh_distance函数计算点到网格的距离和最近的点索引
  File "/data22/DISCOVER_summer2023/wangzd2306/ECON/lib/dataset/Evaluator.py", line 213, in point_mesh_distance
    verts_packed = meshes.verts_packed()
  File "/data22/DISCOVER_summer2023/wangzd2306/.conda/envs/nerfecon/lib/python3.8/site-packages/pytorch3d/structures/meshes.py", line 563, in verts_packed
    self._compute_packed()
  File "/data22/DISCOVER_summer2023/wangzd2306/.conda/envs/nerfecon/lib/python3.8/site-packages/pytorch3d/structures/meshes.py", line 974, in _compute_packed
    verts_list = self.verts_list()
  File "/data22/DISCOVER_summer2023/wangzd2306/.conda/envs/nerfecon/lib/python3.8/site-packages/pytorch3d/structures/meshes.py", line 535, in verts_list
    self._verts_list = struct_utils.padded_to_list(
  File "/data22/DISCOVER_summer2023/wangzd2306/.conda/envs/nerfecon/lib/python3.8/site-packages/pytorch3d/structures/utils.py", line 106, in padded_to_list
    raise ValueError("Split size must be of same length as inputs first dimension")
```

This valueerror raised from the query function and the point_mesh_distance function in pointfeat.py line 39
I am curious about the reason for the error 
Is this because of the pytorch3d version since i am using 0.7.1 or the incorrect dataset input? 

Thanks for any instruction!

**Comment by Wangzeda** [comment]
Oh, i think i find the error, the self.mesh.shape is (1,0,3);
I think maybe i need to re download the dataset

Thanks !
