### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by torealise** [YuliangXiu/ECON#82]
I installed ECON for Blender and when I press "Generate 3D model" i get an error "AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'"

-------------

(ECON_38_env) C:\Users\name\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\CEB_ECON-main\ECON>python -m apps.infer -cfg ./configs/econ.yaml -in_dir ./examples -out_dir ./results

Resume Normal Estimator from  ./data/ckpt/normal.ckpt
Resume IF-Net+ from  ./data/ckpt/ifnet.ckpt
Complete with  IF-Nets+ (Implicit)
SMPL-X estimate with  PIXIE
Dataset Size: 1

Created TensorFlow Lite XNNPACK delegate for CPU.
Body Fitting -- normal: 0.027 | silhouette: 0.024 | joint: 0.039 | Total: 0.089| loose:0, occluded:0:  98%|

examples\image01:
 
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\CEB_ECON-main\ECON\apps\infer.py", line 343, in <module>
    get_optim_grid_image(per_loop_lst, None, nrow=N_body * 2, type="smpl")
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\CEB_ECON-main\ECON\lib\dataset\mesh_util.py", line 668, in get_optim_grid_image
    grid_img = grid_img.resize((grid_img.size[0], grid_img.size[1]), Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

Cannot read from OBJ file:'C:\Users\name\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\CEB_ECON-main\ECON\results\econ\obj\image01_0_full.obj'.
OBJ import of 'image01_0_full.obj' took 0.3 ms

**Comment by torealise** [comment]
I resolved it by downgrading Pillow from 10.0.0 to 9.5.0
